import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ChangePasswordSection } from "../components/account/change-password-section";
import { PlanSection } from "../components/account/plan-section";
import { ProfileSection } from "../components/account/profile-section";
import { DeleteAccountSection } from "../components/delete-account-section";
import { PageLayout } from "../components/page-layout";
import { TelegramLinkSection } from "../components/telegram-link-section";
import { TwoFactorSettings } from "../components/two-factor-settings";
import { api } from "../lib/api";
import { apiErrorMessage } from "../lib/api-error";
import { signOut, useSession } from "../lib/auth-client";
import { hasActivePlan } from "../lib/plan";
import { useMeQuery } from "../lib/queries";
import { requireAuth } from "../lib/require-auth";
import { useAppConfig } from "../lib/use-app-config";

export const Route = createFileRoute("/minha-conta")({
	head: () => ({ meta: [{ title: "Minha conta — Money" }] }),
	beforeLoad: requireAuth,
	component: ProfilePage,
});

function ProfilePage() {
	const { data: session } = useSession();
	const { data: config } = useAppConfig();
	const navigate = useNavigate();
	const meQuery = useMeQuery();

	if (!session || !meQuery.data) return null;
	const me = meQuery.data;

	async function handleDeleteAccount(): Promise<void> {
		const { error } = await api.users.me.delete();
		if (error) throw new Error(apiErrorMessage(error, "Não foi possível excluir sua conta"));

		await signOut();
		await navigate({ to: "/" });
	}

	return (
		<PageLayout>
			<section className="mx-auto max-w-2xl px-4 py-16">
				<h1 className="text-3xl font-bold">Minha conta</h1>

				<ProfileSection name={session.user.name} email={session.user.email} />
				<ChangePasswordSection autoGeneratedPassword={me.autoGeneratedPassword} />
				<PlanSection
					planStatus={me.planStatus}
					planExpiresAt={me.planExpiresAt}
					freeTransactionCount={me.freeTransactionCount}
				/>

				{config?.enable2FA && (
					<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
						<h2 className="text-lg font-semibold">Autenticação em duas etapas</h2>
						<div className="mt-4">
							<TwoFactorSettings enabled={Boolean(session.user.twoFactorEnabled)} />
						</div>
					</div>
				)}

				<TelegramLinkSection telegramChatId={me.telegramChatId} />
				<DeleteAccountSection hasActivePlan={hasActivePlan(me)} onConfirm={handleDeleteAccount} />
			</section>
		</PageLayout>
	);
}
