import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { z } from "zod";
import { AccordionCard } from "../components/accordion-card";
import { FormField, inputClassName } from "../components/auth-card";
import { DeleteAccountSection } from "../components/delete-account-section";
import { PageLayout } from "../components/page-layout";
import { PasswordInput } from "../components/password-input";
import { isStrongPassword, PasswordStrengthInput } from "../components/password-strength-input";
import { TwoFactorSettings } from "../components/two-factor-settings";
import { api } from "../lib/api";
import { authClient, signOut, useSession } from "../lib/auth-client";
import { translateAuthError } from "../lib/auth-errors";
import { FREE_TRANSACTION_LIMIT, hasActivePlan } from "../lib/plan";
import { requireAuth } from "../lib/require-auth";
import { useAppConfig } from "../lib/use-app-config";

export const Route = createFileRoute("/minha-conta")({
	head: () => ({ meta: [{ title: "Minha conta — Money" }] }),
	beforeLoad: requireAuth,
	component: ProfilePage,
});

const nameSchema = z.object({ name: z.string().trim().min(1, "Informe seu nome") });
const telegramChatIdSchema = z.object({
	telegramChatId: z.string().trim().regex(/^\d*$/, "Chat ID inválido — use apenas números"),
});

const passwordSchema = z
	.object({
		currentPassword: z.string().min(1, "Informe sua senha atual"),
		newPassword: z.string().refine(isStrongPassword, "A senha não atende aos requisitos abaixo"),
		confirmPassword: z.string(),
	})
	.refine((data) => data.newPassword === data.confirmPassword, {
		message: "As senhas não coincidem",
		path: ["confirmPassword"],
	});

const paymentEventLabels: Record<string, string> = {
	succeeded: "Pagamento confirmado",
	expired: "PIX expirado",
};

function ProfilePage() {
	const { data: session } = useSession();
	const { data: config } = useAppConfig();
	const navigate = useNavigate();
	const queryClient = useQueryClient();

	const [nameError, setNameError] = useState<string | null>(null);
	const [nameSaved, setNameSaved] = useState(false);
	const [telegramError, setTelegramError] = useState<string | null>(null);
	const [telegramSaved, setTelegramSaved] = useState(false);

	const [currentPassword, setCurrentPassword] = useState("");
	const [newPassword, setNewPassword] = useState("");
	const [confirmPassword, setConfirmPassword] = useState("");
	const [passwordErrors, setPasswordErrors] = useState<Record<string, string>>({});
	const [passwordSaved, setPasswordSaved] = useState(false);

	const meQuery = useQuery({
		queryKey: ["me"],
		queryFn: async () => {
			const { data, error } = await api.users.me.get();
			if (error || !data || !("user" in data)) throw error ?? new Error("Falha ao carregar dados da conta");
			return data.user;
		},
	});

	const historyQuery = useQuery({
		queryKey: ["payment-history"],
		queryFn: async () => {
			const { data, error } = await api.payments.history.get();
			if (error || !data || !("logs" in data)) throw error ?? new Error("Falha ao carregar histórico");
			return data.logs;
		},
	});

	// Conta criada só via Google ganha uma senha forte gerada automaticamente
	// no backend (ver databaseHooks.account.create em auth.ts) — pré-preenche
	// o campo "senha atual" com ela pra o usuário não precisar descobrir essa
	// senha sozinho. Some assim que ele definir a própria senha.
	useEffect(() => {
		if (meQuery.data?.autoGeneratedPassword) {
			setCurrentPassword(meQuery.data.autoGeneratedPassword);
		}
	}, [meQuery.data?.autoGeneratedPassword]);

	if (!session || !meQuery.data) return null;

	const me = meQuery.data;
	const userHasActivePlan = hasActivePlan(me);

	async function handleUpdateName(event: React.FormEvent<HTMLFormElement>): Promise<void> {
		event.preventDefault();
		setNameSaved(false);
		setNameError(null);

		const result = nameSchema.safeParse({ name: new FormData(event.currentTarget).get("name") });

		if (!result.success) {
			setNameError(result.error.issues[0]?.message ?? "Nome inválido");
			return;
		}

		const { error } = await authClient.updateUser({ name: result.data.name });

		if (error) {
			setNameError(translateAuthError(error, "Não foi possível atualizar seu nome"));
			return;
		}

		setNameSaved(true);
	}

	async function handleUpdateTelegramChatId(event: React.FormEvent<HTMLFormElement>): Promise<void> {
		event.preventDefault();
		setTelegramSaved(false);
		setTelegramError(null);

		const raw = new FormData(event.currentTarget).get("telegramChatId");
		const result = telegramChatIdSchema.safeParse({ telegramChatId: raw });

		if (!result.success) {
			setTelegramError(result.error.issues[0]?.message ?? "Chat ID inválido");
			return;
		}

		const { error } = await api.users.me.put({ telegramChatId: result.data.telegramChatId });

		if (error) {
			setTelegramError("Não foi possível salvar o Chat ID do Telegram");
			return;
		}

		setTelegramSaved(true);
		await queryClient.invalidateQueries({ queryKey: ["me"] });
	}

	async function handleChangePassword(event: React.FormEvent<HTMLFormElement>): Promise<void> {
		event.preventDefault();
		setPasswordSaved(false);
		setPasswordErrors({});

		const result = passwordSchema.safeParse({ currentPassword, newPassword, confirmPassword });

		if (!result.success) {
			const fieldErrors: Record<string, string> = {};
			for (const issue of result.error.issues) {
				const key = issue.path[0];
				if (typeof key === "string") fieldErrors[key] = issue.message;
			}
			setPasswordErrors(fieldErrors);
			return;
		}

		const { error } = await authClient.changePassword({
			currentPassword: result.data.currentPassword,
			newPassword: result.data.newPassword,
			revokeOtherSessions: true,
		});

		if (error) {
			setPasswordErrors({ currentPassword: translateAuthError(error, "Não foi possível alterar sua senha") });
			return;
		}

		setCurrentPassword("");
		setNewPassword("");
		setConfirmPassword("");
		setPasswordSaved(true);
	}

	async function handleDeleteAccount(): Promise<void> {
		const { data, error } = await api.users.me.delete();

		if (error || !data?.success) {
			throw new Error(
				(data as { message?: string } | undefined)?.message ?? "Não foi possível excluir sua conta",
			);
		}

		await signOut();
		await navigate({ to: "/" });
	}

	return (
		<PageLayout>
			<section className="mx-auto max-w-2xl px-4 py-16">
				<h1 className="text-3xl font-bold">Minha conta</h1>

				<div className="mt-8 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
					<h2 className="text-lg font-semibold">Dados da conta</h2>

					<form onSubmit={handleUpdateName} className="mt-4 flex flex-col gap-4">
						{nameError && <p className="text-sm text-red-500">{nameError}</p>}
						{nameSaved && <p className="text-sm text-brand-600">Nome atualizado com sucesso.</p>}

						<FormField label="Nome" id="name">
							<input
								id="name"
								name="name"
								type="text"
								defaultValue={session.user.name}
								className={inputClassName}
							/>
						</FormField>

						<FormField label="E-mail" id="email">
							<input
								id="email"
								type="email"
								value={session.user.email}
								disabled
								className={`${inputClassName} opacity-60`}
							/>
						</FormField>

						<button
							type="submit"
							className="self-start rounded-lg bg-brand-500 px-4 py-2 font-semibold text-black hover:bg-brand-400"
						>
							Salvar
						</button>
					</form>
				</div>

				<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
					<h2 className="text-lg font-semibold">Alterar senha</h2>

					<form onSubmit={handleChangePassword} className="mt-4 flex flex-col gap-4">
						{passwordSaved && <p className="text-sm text-brand-600">Senha alterada com sucesso.</p>}

						{me.autoGeneratedPassword && (
							<p className="rounded-lg bg-blue-500/10 px-3 py-2 text-sm text-blue-600" role="status">
								Como você criou sua conta com o Google, essa é sua senha atual que foi gerada
								automaticamente.
							</p>
						)}

						<FormField label="Senha atual" id="currentPassword" error={passwordErrors.currentPassword}>
							<PasswordInput
								id="currentPassword"
								name="currentPassword"
								value={currentPassword}
								onChange={setCurrentPassword}
							/>
						</FormField>

						<FormField label="Nova senha" id="newPassword" error={passwordErrors.newPassword}>
							<PasswordStrengthInput
								id="newPassword"
								name="newPassword"
								value={newPassword}
								onChange={setNewPassword}
								placeholder="Crie uma nova senha forte"
							/>
						</FormField>

						<FormField
							label="Confirmar nova senha"
							id="confirmPassword"
							error={passwordErrors.confirmPassword}
						>
							<PasswordInput
								id="confirmPassword"
								name="confirmPassword"
								value={confirmPassword}
								onChange={setConfirmPassword}
							/>
						</FormField>

						<button
							type="submit"
							className="self-start rounded-lg bg-brand-500 px-4 py-2 font-semibold text-black hover:bg-brand-400"
						>
							Alterar senha
						</button>
					</form>
				</div>

				<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
					<h2 className="text-lg font-semibold">Plano</h2>

					{userHasActivePlan ? (
						<p className="mt-3 text-sm text-(--color-fg-muted)">
							Plano <strong className="text-(--color-fg)">PRO</strong> ativo até{" "}
							{me.planExpiresAt ? new Date(me.planExpiresAt).toLocaleDateString("pt-BR") : "—"}.
						</p>
					) : (
						<>
							<p className="mt-2 text-sm text-(--color-fg-muted)">
								Plano atual: <strong className="text-(--color-fg)">Gratuito</strong> —{" "}
								{me.freeTransactionCount}/{FREE_TRANSACTION_LIMIT} transações utilizadas.
							</p>
							{me.freeTransactionCount >= FREE_TRANSACTION_LIMIT && (
								<p className="mt-2 text-sm text-red-500">
									Limite de transações gratuitas atingido — assine um plano para liberar acesso
									ilimitado.
								</p>
							)}
							{(config?.enableAbacatepay || config?.abacatepayPixTestMode) && (
								<Link
									to="/checkout"
									className="mt-4 inline-block rounded-lg bg-orange-500 px-5 py-2.5 text-sm font-bold text-white hover:bg-orange-400"
								>
									Assinar Plano
								</Link>
							)}
						</>
					)}

					{historyQuery.data?.some((log) => log.status === "succeeded" || log.status === "expired") && (
						<div className="mt-5 border-t border-(--color-border) pt-4">
							<AccordionCard title="Histórico de pagamentos">
								<ul className="flex flex-col gap-2">
									{historyQuery.data
										.filter((log) => log.status === "succeeded" || log.status === "expired")
										.map((log) => (
											<li
												key={log.id}
												className="flex items-center justify-between text-sm text-(--color-fg-muted)"
											>
												<span>
													{paymentEventLabels[log.status] ?? log.status}
													{log.amount != null
														? ` — ${(log.amount / 100).toFixed(2)} ${(log.currency ?? "").toUpperCase()}`
														: ""}
												</span>
												<span>{new Date(log.createdAt).toLocaleString("pt-BR")}</span>
											</li>
										))}
								</ul>
							</AccordionCard>
						</div>
					)}
				</div>

				{config?.enable2FA && (
					<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
						<h2 className="text-lg font-semibold">Autenticação em duas etapas</h2>
						<div className="mt-4">
							<TwoFactorSettings enabled={Boolean(session.user.twoFactorEnabled)} />
						</div>
					</div>
				)}

				<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
					<h2 className="text-lg font-semibold">Bot do Telegram</h2>
					<p className="mt-2 text-sm text-(--color-fg-muted)">
						Abra o bot no Telegram e envie o ID da conta abaixo quando ele pedir — isso vincula as
						transações feitas pelo bot à sua conta. Você também pode informar o Chat ID manualmente aqui.
					</p>

					<div className="mt-3 rounded-lg border border-(--color-border) bg-(--color-bg-subtle) p-3">
						<p className="text-xs font-medium text-(--color-fg-muted)">ID da conta</p>
						<code className="mt-1 block break-all text-xs">{me.id}</code>
					</div>

					<form onSubmit={handleUpdateTelegramChatId} className="mt-4 flex flex-col gap-4">
						{telegramError && <p className="text-sm text-red-500">{telegramError}</p>}
						{telegramSaved && <p className="text-sm text-brand-600">Chat ID salvo com sucesso.</p>}

						<FormField label="Chat ID do Telegram" id="telegramChatId">
							<input
								id="telegramChatId"
								name="telegramChatId"
								type="text"
								inputMode="numeric"
								pattern="\d*"
								defaultValue={me.telegramChatId ?? ""}
								onInput={(event) => {
									event.currentTarget.value = event.currentTarget.value.replace(/\D/g, "");
								}}
								placeholder="Ex: 123456789"
								className={inputClassName}
							/>
						</FormField>

						<button
							type="submit"
							className="self-start rounded-lg bg-brand-500 px-4 py-2 font-semibold text-black hover:bg-brand-400"
						>
							Salvar
						</button>
					</form>
				</div>

				<DeleteAccountSection hasActivePlan={userHasActivePlan} onConfirm={handleDeleteAccount} />
			</section>
		</PageLayout>
	);
}
