import { useEffect, useState } from "react";
import { z } from "zod";
import { authClient } from "../../lib/auth-client";
import { translateAuthError } from "../../lib/auth-errors";
import { FormField } from "../auth-card";
import { PasswordInput } from "../password-input";
import { isStrongPassword, PasswordStrengthInput } from "../password-strength-input";

const passwordSchema = z
	.object({
		currentPassword: z.string().min(1, "Informe sua senha atual"),
		newPassword: z.string().refine(isStrongPassword, "A senha não atende aos requisitos abaixo"),
		confirmPassword: z.string(),
	})
	.refine((data) => data.newPassword === data.confirmPassword, {
		message: "As senhas não coincidem",
		path: ["confirmPassword"],
	});

/**
 * Google-only accounts get a generated password on the backend (see
 * databaseHooks.account.create in backend/src/lib/auth.ts) — it prefills
 * "current password" so the user never has to discover it. The backend
 * clears it once they set their own.
 */
export function ChangePasswordSection({ autoGeneratedPassword }: { autoGeneratedPassword: string | null }) {
	const [currentPassword, setCurrentPassword] = useState("");
	const [newPassword, setNewPassword] = useState("");
	const [confirmPassword, setConfirmPassword] = useState("");
	const [errors, setErrors] = useState<Record<string, string>>({});
	const [saved, setSaved] = useState(false);

	useEffect(() => {
		if (autoGeneratedPassword) setCurrentPassword(autoGeneratedPassword);
	}, [autoGeneratedPassword]);

	async function handleSubmit(event: React.FormEvent<HTMLFormElement>): Promise<void> {
		event.preventDefault();
		setSaved(false);
		setErrors({});

		const result = passwordSchema.safeParse({ currentPassword, newPassword, confirmPassword });
		if (!result.success) {
			const fieldErrors: Record<string, string> = {};
			for (const issue of result.error.issues) {
				const key = issue.path[0];
				if (typeof key === "string") fieldErrors[key] = issue.message;
			}
			setErrors(fieldErrors);
			return;
		}

		const { error } = await authClient.changePassword({
			currentPassword: result.data.currentPassword,
			newPassword: result.data.newPassword,
			revokeOtherSessions: true,
		});

		if (error) {
			setErrors({ currentPassword: translateAuthError(error, "Não foi possível alterar sua senha") });
			return;
		}

		setCurrentPassword("");
		setNewPassword("");
		setConfirmPassword("");
		setSaved(true);
	}

	return (
		<div className="mt-6 rounded-2xl border border-(--color-border) bg-(--color-surface) p-6">
			<h2 className="text-lg font-semibold">Alterar senha</h2>

			<form onSubmit={handleSubmit} className="mt-4 flex flex-col gap-4">
				{saved && <p className="text-sm text-brand-600">Senha alterada com sucesso.</p>}

				{autoGeneratedPassword && (
					<p className="rounded-lg bg-blue-500/10 px-3 py-2 text-sm text-blue-600" role="status">
						Como você criou sua conta com o Google, essa é sua senha atual que foi gerada automaticamente.
					</p>
				)}

				<FormField label="Senha atual" id="currentPassword" error={errors.currentPassword}>
					<PasswordInput
						id="currentPassword"
						name="currentPassword"
						value={currentPassword}
						onChange={setCurrentPassword}
					/>
				</FormField>

				<FormField label="Nova senha" id="newPassword" error={errors.newPassword}>
					<PasswordStrengthInput
						id="newPassword"
						name="newPassword"
						value={newPassword}
						onChange={setNewPassword}
						placeholder="Crie uma nova senha forte"
					/>
				</FormField>

				<FormField label="Confirmar nova senha" id="confirmPassword" error={errors.confirmPassword}>
					<PasswordInput
						id="confirmPassword"
						name="confirmPassword"
						value={confirmPassword}
						onChange={setConfirmPassword}
					/>
				</FormField>

				<button
					type="submit"
					className="self-start rounded-lg bg-brand-500 px-4 py-2 font-semibold text-black hover:bg-brand-400"
				>
					Alterar senha
				</button>
			</form>
		</div>
	);
}
