import { prisma } from "../src/config/prisma";
import { decryptIfEncrypted, encrypt } from "../src/lib/encryption";

/**
 * One-off, idempotent: encrypts `user.autoGeneratedPassword` values written in
 * plaintext before encryption at rest was introduced (reads already tolerate
 * both formats via decryptIfEncrypted). Run once per environment:
 * `bun run scripts/encrypt-auto-generated-passwords.ts`
 */
async function main(): Promise<void> {
	const users = await prisma.user.findMany({
		where: { autoGeneratedPassword: { not: null } },
		select: { id: true, autoGeneratedPassword: true },
	});

	let migrated = 0;
	for (const user of users) {
		const value = user.autoGeneratedPassword;
		if (!value || decryptIfEncrypted(value) !== value) continue;

		await prisma.user.update({ where: { id: user.id }, data: { autoGeneratedPassword: encrypt(value) } });
		migrated++;
	}

	console.log(`Encrypted ${migrated} of ${users.length} auto-generated password(s).`);
}

main()
	.catch((error) => {
		console.error(error);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
