import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { BottomNav } from "@/components/ui/bottom-nav";
import { Button } from "@/components/ui/button";
import { Notice } from "@/components/ui/notice";
import { Row, Section, SectionBody } from "@/components/ui/section";
import { TextField } from "@/components/ui/text-field";
import { api } from "@/lib/api";
import { authClient, useSession } from "@/lib/auth-client";
import { translateAuthError } from "@/lib/auth-errors";
import { isStrongPassword } from "@/lib/password-rules";
import { FREE_TRANSACTION_LIMIT, hasActivePlan, planRemainingLabel } from "@/lib/plan";
import { useMeQuery, useRefreshMe } from "@/query/me";

type Feedback = { kind: "error" | "success"; message: string } | null;

export default function ProfileScreen() {
	const router = useRouter();
	const { data: session } = useSession();
	const meQuery = useMeQuery();
	const refreshMe = useRefreshMe();
	const me = meQuery.data;

	const [name, setName] = useState(session?.user.name ?? "");
	const [nameFeedback, setNameFeedback] = useState<Feedback>(null);
	const [savingName, setSavingName] = useState(false);

	const [currentPassword, setCurrentPassword] = useState("");
	const [newPassword, setNewPassword] = useState("");
	const [passwordFeedback, setPasswordFeedback] = useState<Feedback>(null);
	const [savingPassword, setSavingPassword] = useState(false);

	const [telegramFeedback, setTelegramFeedback] = useState<Feedback>(null);

	// Google-only accounts get a generated password on the backend; prefill it
	// so the user can change it without discovering it first.
	useEffect(() => {
		if (me?.autoGeneratedPassword) setCurrentPassword(me.autoGeneratedPassword);
	}, [me?.autoGeneratedPassword]);

	async function onSaveName(): Promise<void> {
		setNameFeedback(null);
		setSavingName(true);
		const { error } = await authClient.updateUser({ name: name.trim() });
		setSavingName(false);
		setNameFeedback(
			error
				? { kind: "error", message: translateAuthError(error, "Não foi possível atualizar seu nome") }
				: { kind: "success", message: "Nome atualizado." },
		);
	}

	async function onChangePassword(): Promise<void> {
		setPasswordFeedback(null);
		if (!currentPassword || !isStrongPassword(newPassword)) {
			setPasswordFeedback({
				kind: "error",
				message: "A nova senha precisa ter 8-32 caracteres, maiúscula, minúscula, número e símbolo.",
			});
			return;
		}

		setSavingPassword(true);
		const { error } = await authClient.changePassword({ currentPassword, newPassword, revokeOtherSessions: true });
		setSavingPassword(false);

		if (error) {
			setPasswordFeedback({
				kind: "error",
				message: translateAuthError(error, "Não foi possível alterar sua senha"),
			});
			return;
		}
		setPasswordFeedback({ kind: "success", message: "Senha alterada com sucesso." });
		setCurrentPassword("");
		setNewPassword("");
		await refreshMe();
	}

	async function onUnlinkTelegram(): Promise<void> {
		setTelegramFeedback(null);
		const { error } = await api.telegram.link.delete();
		if (error) {
			setTelegramFeedback({ kind: "error", message: "Não foi possível desvincular o Telegram." });
			return;
		}
		setTelegramFeedback({ kind: "success", message: "Telegram desvinculado." });
		await refreshMe();
	}

	function onLogout(): void {
		Alert.alert("Sair da conta", "Deseja realmente desconectar esta conta?", [
			{ text: "Cancelar", style: "cancel" },
			{
				text: "Sair",
				style: "destructive",
				onPress: async () => {
					await authClient.signOut();
					router.replace("/login");
				},
			},
		]);
	}

	function onDeleteAccount(): void {
		if (me && hasActivePlan(me)) {
			Alert.alert("Plano ativo", "Aguarde o vencimento do plano antes de excluir sua conta.");
			return;
		}

		Alert.alert(
			"Excluir conta",
			"Sua conta será marcada para exclusão. Você tem 30 dias para entrar novamente e cancelar; depois disso, a exclusão é definitiva.",
			[
				{ text: "Cancelar", style: "cancel" },
				{
					text: "Excluir",
					style: "destructive",
					onPress: async () => {
						const { error } = await api.users.me.delete();
						if (error) {
							Alert.alert("Erro", "Não foi possível excluir sua conta.");
							return;
						}
						await authClient.signOut();
						router.replace("/login");
					},
				},
			],
		);
	}

	const activePlan = me ? hasActivePlan(me) : false;
	const remaining = me ? planRemainingLabel(me) : null;
	const planValue = activePlan
		? `PRO${remaining ? ` · ${remaining}` : ""}`
		: `Gratuito · ${me?.freeTransactionCount ?? 0}/${FREE_TRANSACTION_LIMIT}`;

	return (
		<SafeAreaView className="flex-1 bg-canvas" edges={["left", "right"]}>
			<KeyboardAvoidingView className="flex-1" behavior={Platform.OS === "ios" ? "padding" : undefined}>
				<ScrollView contentContainerClassName="gap-7 px-5 py-4" keyboardShouldPersistTaps="handled">
					<View className="items-center gap-2 py-2">
						<View className="size-16 items-center justify-center rounded-full bg-raised">
							<Text className="text-title text-fg">
								{(session?.user.name ?? "?").charAt(0).toUpperCase()}
							</Text>
						</View>
						<Text className="text-headline text-fg">{session?.user.name}</Text>
						<Text className="text-subhead text-subtle">{session?.user.email}</Text>
					</View>

					<Section title="Plano">
						<Row
							label="Assinatura"
							value={planValue}
							icon="star"
							onPress={() => router.push("/subscription")}
							last
						/>
					</Section>

					<Section title="Perfil">
						<SectionBody>
							<TextField
								label="Nome"
								value={name}
								onChangeText={setName}
								placeholder="Como devemos te chamar?"
								maxLength={16}
							/>
							<Notice kind={nameFeedback?.kind ?? "error"} message={nameFeedback?.message} />
							<Button
								label="Salvar nome"
								variant="secondary"
								size="md"
								onPress={onSaveName}
								loading={savingName}
								disabled={!name.trim()}
							/>
						</SectionBody>
					</Section>

					<Section title="Segurança">
						<Row
							label="Verificação em duas etapas"
							value={me?.twoFactorEnabled ? "Ativa" : "Desativada"}
							icon="shield"
							onPress={() => router.push("/two-factor")}
							last
						/>
					</Section>

					<Section
						title="Alterar senha"
						footer={
							me?.autoGeneratedPassword
								? "Sua conta foi criada com o Google — a senha atual gerada automaticamente já está preenchida."
								: undefined
						}
					>
						<SectionBody>
							<TextField
								label="Senha atual"
								value={currentPassword}
								onChangeText={setCurrentPassword}
								placeholder="Sua senha atual"
								autoComplete="current-password"
								secureTextEntry
							/>
							<TextField
								label="Nova senha"
								value={newPassword}
								onChangeText={setNewPassword}
								placeholder="Crie uma nova senha forte"
								autoComplete="new-password"
								secureTextEntry
							/>
							<Notice kind={passwordFeedback?.kind ?? "error"} message={passwordFeedback?.message} />
							<Button
								label="Alterar senha"
								variant="secondary"
								size="md"
								onPress={onChangePassword}
								loading={savingPassword}
							/>
						</SectionBody>
					</Section>

					<Section
						title="Bot do Telegram"
						footer={
							me?.telegramChatId
								? "As transações feitas pelo bot entram nesta conta."
								: "Nenhum chat vinculado. Abra o bot no Telegram e entre com seu e-mail e senha."
						}
					>
						<Row
							label={me?.telegramChatId ? "Chat vinculado" : "Não vinculado"}
							icon="send"
							value={me?.telegramChatId ? "Desvincular" : undefined}
							onPress={me?.telegramChatId ? onUnlinkTelegram : undefined}
							last
						/>
					</Section>
					<Notice kind={telegramFeedback?.kind ?? "error"} message={telegramFeedback?.message} />

					<Section footer="Excluir marca a conta para exclusão definitiva após 30 dias.">
						<Row label="Sair da conta" icon="log-out" onPress={onLogout} destructive />
						<Row label="Excluir minha conta" icon="trash-2" onPress={onDeleteAccount} destructive last />
					</Section>
				</ScrollView>
			</KeyboardAvoidingView>

			<BottomNav active="profile" />
		</SafeAreaView>
	);
}
