import { randomUUID } from "node:crypto";
import { apiKey } from "@better-auth/api-key";
import { expo } from "@better-auth/expo";
import { render } from "@react-email/render";
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { hashPassword } from "better-auth/crypto";
import { twoFactor } from "better-auth/plugins";
import { env } from "../config/env";
import { prisma } from "../config/prisma";
import { ResetPasswordEmail } from "../emails/reset-password";
import { TwoFactorOtpEmail } from "../emails/two-factor-otp";
import { VerifyEmail } from "../emails/verify-email";
import { generateStrongPassword } from "./generate-password";
import { sendEmail } from "./resend";

export const auth = betterAuth({
	// `baseURL` (não `APP_URL`) de propósito: é a partir dele que o better-auth
	// monta o `redirect_uri` enviado ao Google e os links de verify-email/
	// reset-password. Como o navegador só fala com o domínio do frontend (que
	// faz proxy de `/auth/*` pra API — ver frontend/proxy-paths.ts), qualquer
	// uma dessas URLs apontando pro domínio da API pula o proxy: o cookie de
	// `state` do OAuth (setado durante o proxy) nunca chega no callback do
	// Google, que bate direto na API, e o browser devolve `state_mismatch`.
	baseURL: env.FRONTEND_URL,
	basePath: "/auth",
	secret: env.BETTER_AUTH_SECRET,
	// "money://" é o scheme do app mobile (Expo) — precisa estar aqui pro
	// redirect de volta ao app depois do login social (Google) ser aceito.
	trustedOrigins: [env.FRONTEND_URL, "money://"],
	advanced: {
		// Railway já resolve o IP real do cliente e o expõe em `x-real-ip`
		// (sempre um único valor, sobrescrito pelo edge — não repassado
		// como veio do cliente), então não precisamos configurar
		// `trustedProxies` com os ranges de IP do proxy da Railway.
		ipAddress: {
			ipAddressHeaders: ["x-real-ip", "x-forwarded-for"],
		},
		// Frontend e backend são domínios distintos no Railway
		// (*.up.railway.app não compartilha um domínio-pai comum entre os
		// serviços), então o cookie de sessão é sempre cross-site do ponto
		// de vista do navegador. Com o padrão `SameSite=Lax`, o navegador
		// guarda o cookie no login (resposta do POST) mas não o reenvia em
		// chamadas subsequentes via fetch/XHR cross-site (só em navegação
		// de topo) — por isso o /auth/get-session seguinte não via a sessão
		// e o dashboard redirecionava de volta pro login. `SameSite=None`
		// exige `Secure`, que já está implícito em produção.
		defaultCookieAttributes: {
			sameSite: "none",
			secure: true,
		},
	},
	database: prismaAdapter(prisma, {
		provider: env.DATABASE_PROVIDER,
	}),
	emailAndPassword: {
		enabled: true,
		requireEmailVerification: env.ENABLE_CONFIRM_EMAIL,
		sendResetPassword: async ({ user, url }) => {
			await sendEmail({
				to: user.email,
				subject: "Redefinir sua senha",
				html: await render(ResetPasswordEmail({ resetUrl: url })),
			});
		},
		// Cobre o "esqueci minha senha": o usuário definiu uma senha própria,
		// então a automática (gerada pra contas só-Google) não é mais válida.
		// O fluxo de troca de senha logado (change-password) é tratado à parte
		// em auth.plugin.ts — esse hook aqui só dispara no reset por token.
		onPasswordReset: async ({ user }) => {
			await prisma.user.updateMany({
				where: { id: user.id, autoGeneratedPassword: { not: null } },
				data: { autoGeneratedPassword: null },
			});
		},
	},
	emailVerification: {
		sendOnSignUp: env.ENABLE_CONFIRM_EMAIL,
		autoSignInAfterVerification: true,
		sendVerificationEmail: async ({ user, url }) => {
			await sendEmail({
				to: user.email,
				subject: "Confirme seu e-mail",
				html: await render(VerifyEmail({ verifyUrl: url })),
			});
		},
	},
	socialProviders: {
		...(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET
			? {
					google: {
						clientId: env.GOOGLE_CLIENT_ID,
						clientSecret: env.GOOGLE_CLIENT_SECRET,
					},
				}
			: {}),
	},
	plugins: [
		// Precisa ser o primeiro plugin da lista (exigência do @better-auth/expo):
		// sobrescreve a origem das rotas /auth/* chamadas pelo app mobile (que não
		// tem um Origin de navegador de verdade) e expõe o proxy de autorização
		// usado pelo login social (Google) dentro do WebBrowser do Expo.
		expo(),
		apiKey({ enableSessionForAPIKeys: true }),
		...(env.ENABLE_2FA
			? [
					twoFactor({
						issuer: "Elysia Finanças",
						otpOptions: {
							async sendOTP({ user, otp }) {
								await sendEmail({
									to: user.email,
									subject: "Seu código de verificação",
									html: await render(TwoFactorOtpEmail({ code: otp })),
								});
							},
						},
					}),
				]
			: []),
	],
	session: {
		expiresIn: 60 * 60 * 24 * 7,
		updateAge: 60 * 60 * 24,
	},
	databaseHooks: {
		session: {
			create: {
				// Login (e-mail/senha ou Google) dentro dos 30 dias de carência
				// cancela um pedido de exclusão de conta pendente (Fase 6).
				async after(session) {
					await prisma.user.updateMany({
						where: { id: session.userId, deletionRequestedAt: { not: null } },
						data: { deletionRequestedAt: null },
					});
				},
			},
		},
		account: {
			create: {
				// Conta criada só via Google (sem credential ainda) ganha uma senha
				// forte gerada automaticamente, pra habilitar tanto login por
				// e-mail/senha quanto o 2FA (que exige senha pra ativar/desativar).
				// O valor em claro fica em `user.autoGeneratedPassword` só até o
				// usuário definir a própria senha (ver onPasswordReset acima e o
				// wrapper de /change-password em auth.plugin.ts) e o card de
				// "Alterar senha" em /minha-conta.
				async after(account) {
					if (account.providerId === "credential") return;

					const existingCredential = await prisma.account.findFirst({
						where: { userId: account.userId, providerId: "credential" },
					});
					if (existingCredential) return;

					const plainPassword = generateStrongPassword(32);
					await prisma.account.create({
						data: {
							id: randomUUID(),
							userId: account.userId,
							providerId: "credential",
							accountId: account.userId,
							password: await hashPassword(plainPassword),
						},
					});
					await prisma.user.update({
						where: { id: account.userId },
						data: { autoGeneratedPassword: plainPassword },
					});
				},
			},
		},
	},
});

export type Auth = typeof auth;
