import { Elysia } from "elysia";
import { prisma } from "../config/prisma";
import { auth } from "./auth";

// `databaseHooks.account.update` não dá pra usar aqui: o better-auth troca a
// senha via `updateMany` (casa por userId+providerId+accountId, não por id),
// e esse caminho só repassa a CONTAGEM de linhas afetadas pro hook `after`,
// não a conta atualizada — não dá pra checar `providerId`/`password` nela.
// Por isso o /change-password é interceptado aqui: se a troca de senha
// (usuário logado) for bem-sucedida, a senha automática de contas só-Google
// deixa de ser válida e é apagada.
async function handleAuthRequest(request: Request): Promise<Response> {
	const response = await auth.handler(request);

	if (response.ok && new URL(request.url).pathname.endsWith("/change-password")) {
		const session = await auth.api.getSession({ headers: request.headers });
		if (session) {
			await prisma.user.updateMany({
				where: { id: session.user.id, autoGeneratedPassword: { not: null } },
				data: { autoGeneratedPassword: null },
			});
		}
	}

	return response;
}

export const authPlugin = new Elysia({ name: "better-auth" }).mount(handleAuthRequest).macro({
	auth: {
		async resolve({ status, request: { headers } }) {
			const session = await auth.api.getSession({ headers });

			if (!session) {
				return status(401, { success: false, message: "Sessão inválida ou expirada" });
			}

			return {
				user: session.user,
				session: session.session,
			};
		},
	},
});
