import { randomUUID } from "node:crypto";
import { apiKey } from "@better-auth/api-key";
import { expo } from "@better-auth/expo";
import { render } from "@react-email/render";
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { hashPassword } from "better-auth/crypto";
import { twoFactor } from "better-auth/plugins";
import { env } from "../config/env";
import { prisma } from "../config/prisma";
import { ResetPasswordEmail } from "../emails/reset-password";
import { TwoFactorOtpEmail } from "../emails/two-factor-otp";
import { VerifyEmail } from "../emails/verify-email";
import { userRepository } from "../modules/users/user.repository";
import { encrypt } from "./encryption";
import { generateStrongPassword } from "./generate-password";
import { sendEmail } from "./resend";

export const auth = betterAuth({
	// `baseURL` is the FRONTEND on purpose: better-auth builds the Google
	// `redirect_uri` and the verify-email/reset-password links from it. The
	// browser only talks to the frontend domain (which proxies `/auth/*` to
	// the API, see frontend/proxy-paths.ts); any of those URLs pointing at the
	// API domain would skip the proxy, the OAuth `state` cookie (set through
	// the proxy) would never reach the callback, and Google login would fail
	// with `state_mismatch`.
	baseURL: env.FRONTEND_URL,
	basePath: "/auth",
	secret: env.BETTER_AUTH_SECRET,
	// "money://" is the mobile app's (Expo) scheme — required for the redirect
	// back into the app after social login.
	trustedOrigins: [env.FRONTEND_URL, "money://"],
	advanced: {
		// Railway resolves the real client IP into `x-real-ip` (overwritten at
		// the edge, never forwarded from the client). Caddy (infra/Caddyfile)
		// replaces `x-forwarded-for` for untrusted clients. Rate limiting keys
		// on this IP — if the API is ever exposed without one of these proxies
		// in front, `x-forwarded-for` becomes client-controlled.
		ipAddress: {
			ipAddressHeaders: ["x-real-ip", "x-forwarded-for"],
		},
		// Frontend and API live on different Railway domains (*.up.railway.app
		// has no shared parent domain), so the session cookie is cross-site
		// from the browser's point of view. With the default SameSite=Lax the
		// browser stores it on login but never re-sends it on cross-site
		// fetch/XHR, and the dashboard bounced back to the login page.
		// SameSite=None requires Secure. CSRF is covered by better-auth's
		// origin check against `trustedOrigins`.
		defaultCookieAttributes: {
			sameSite: "none",
			secure: true,
		},
	},
	database: prismaAdapter(prisma, {
		provider: env.DATABASE_PROVIDER,
	}),
	emailAndPassword: {
		enabled: true,
		requireEmailVerification: env.ENABLE_CONFIRM_EMAIL,
		sendResetPassword: async ({ user, url }) => {
			await sendEmail({
				to: user.email,
				subject: "Redefinir sua senha",
				html: await render(ResetPasswordEmail({ resetUrl: url })),
			});
		},
		// "Forgot password": the user now has a password of their own, so the
		// auto-generated one (Google-only accounts) is no longer valid. The
		// logged-in change-password flow is handled in auth.plugin.ts — this
		// hook only fires on token-based resets.
		onPasswordReset: async ({ user }) => {
			await userRepository.clearAutoGeneratedPassword(user.id);
		},
	},
	emailVerification: {
		sendOnSignUp: env.ENABLE_CONFIRM_EMAIL,
		autoSignInAfterVerification: true,
		sendVerificationEmail: async ({ user, url }) => {
			await sendEmail({
				to: user.email,
				subject: "Confirme seu e-mail",
				html: await render(VerifyEmail({ verifyUrl: url })),
			});
		},
	},
	socialProviders: {
		...(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET
			? {
					google: {
						clientId: env.GOOGLE_CLIENT_ID,
						clientSecret: env.GOOGLE_CLIENT_SECRET,
					},
				}
			: {}),
	},
	plugins: [
		// Must be the first plugin (@better-auth/expo requirement): it
		// overrides the origin of /auth/* calls from the mobile app (which has
		// no real browser Origin) and exposes the authorization proxy used by
		// social login inside Expo's WebBrowser.
		expo(),
		apiKey({ enableSessionForAPIKeys: true }),
		...(env.ENABLE_2FA
			? [
					twoFactor({
						issuer: "Agent Money Boilerplate",
						otpOptions: {
							async sendOTP({ user, otp }) {
								await sendEmail({
									to: user.email,
									subject: "Seu código de verificação",
									html: await render(TwoFactorOtpEmail({ code: otp })),
								});
							},
						},
					}),
				]
			: []),
	],
	session: {
		expiresIn: 60 * 60 * 24 * 7,
		updateAge: 60 * 60 * 24,
	},
	databaseHooks: {
		session: {
			create: {
				// Logging in during the 30-day grace period cancels a pending
				// account deletion request.
				async after(session) {
					await prisma.user.updateMany({
						where: { id: session.userId, deletionRequestedAt: { not: null } },
						data: { deletionRequestedAt: null },
					});
				},
			},
		},
		account: {
			create: {
				// Google-only accounts get a strong generated password, which
				// enables e-mail/password login and 2FA (which requires a password
				// to toggle). It is kept — encrypted at rest — in
				// `user.autoGeneratedPassword` only until the user sets their own
				// (onPasswordReset above, the change-password wrapper in
				// auth.plugin.ts), so "Minha conta" can show it once.
				async after(account) {
					if (account.providerId === "credential") return;

					const existingCredential = await prisma.account.findFirst({
						where: { userId: account.userId, providerId: "credential" },
					});
					if (existingCredential) return;

					const plainPassword = generateStrongPassword(32);
					await prisma.account.create({
						data: {
							id: randomUUID(),
							userId: account.userId,
							providerId: "credential",
							accountId: account.userId,
							password: await hashPassword(plainPassword),
						},
					});
					await userRepository.update(account.userId, { autoGeneratedPassword: encrypt(plainPassword) });
				},
			},
		},
	},
});

export type Auth = typeof auth;
