import { APIError } from "better-auth";
import { Elysia } from "elysia";
import { userRepository } from "../modules/users/user.repository";
import { auth } from "./auth";

// `databaseHooks.account.update` can't be used for this: better-auth changes
// the password through `updateMany` (matching userId+providerId+accountId),
// and that path only hands the affected ROW COUNT to the `after` hook, not
// the account itself. So /change-password is intercepted here: a successful
// logged-in password change invalidates the auto-generated password of
// Google-only accounts.
//
// The session must be read BEFORE `auth.handler` runs: the frontend sends
// `revokeOtherSessions: true`, which better-auth treats as "revoke ALL
// sessions" — it deletes the current one and issues a new one, so the
// original request's cookies point at a dead session afterwards.
async function handleAuthRequest(request: Request): Promise<Response> {
	const isChangePassword = new URL(request.url).pathname.endsWith("/change-password");
	const sessionBeforeHandler = isChangePassword ? await auth.api.getSession({ headers: request.headers }) : null;

	const response = await auth.handler(request);

	if (response.ok && sessionBeforeHandler) {
		await userRepository.clearAutoGeneratedPassword(sessionBeforeHandler.user.id);
	}

	return response;
}

// An invalid or revoked `x-api-key` makes getSession throw (403
// INVALID_API_KEY) instead of returning null — treat it as unauthenticated
// rather than letting it surface as a 500.
async function resolveSession(headers: Headers) {
	try {
		return await auth.api.getSession({ headers });
	} catch (error) {
		if (error instanceof APIError) return null;
		throw error;
	}
}

export const authPlugin = new Elysia({ name: "better-auth" }).mount(handleAuthRequest).macro({
	auth: {
		async resolve({ status, request: { headers } }) {
			const session = await resolveSession(headers);

			if (!session) {
				return status(401, { success: false, message: "Sessão inválida ou expirada" });
			}

			return {
				user: session.user,
				session: session.session,
			};
		},
	},
});
