import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { env } from "../config/env";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;
const KEY = Buffer.from(env.ENCRYPTION_KEY, "hex");
const PAYLOAD_PATTERN = /^[0-9a-f]{24}:[0-9a-f]{32}:[0-9a-f]*$/i;

/**
 * Encrypts sensitive data before it is persisted (AES-256-GCM). Returns
 * `iv:authTag:ciphertext` in hex in a single string column, so it behaves
 * identically on SQLite and Postgres.
 */
export function encrypt(plainText: string): string {
	const iv = randomBytes(IV_LENGTH);
	const cipher = createCipheriv(ALGORITHM, KEY, iv);
	const ciphertext = Buffer.concat([cipher.update(plainText, "utf8"), cipher.final()]);
	const authTag = cipher.getAuthTag();

	return `${iv.toString("hex")}:${authTag.toString("hex")}:${ciphertext.toString("hex")}`;
}

export function decrypt(payload: string): string {
	const [ivHex, authTagHex, ciphertextHex] = payload.split(":");

	if (!ivHex || !authTagHex || ciphertextHex === undefined) {
		throw new Error("Malformed encrypted payload");
	}

	const decipher = createDecipheriv(ALGORITHM, KEY, Buffer.from(ivHex, "hex"));
	decipher.setAuthTag(Buffer.from(authTagHex, "hex"));

	const plainText = Buffer.concat([decipher.update(Buffer.from(ciphertextHex, "hex")), decipher.final()]);

	return plainText.toString("utf8");
}

/**
 * For columns that used to hold plaintext before encryption at rest was
 * introduced (`user.autoGeneratedPassword`): values that don't look like an
 * `encrypt()` payload are returned as-is instead of failing to decrypt.
 */
export function decryptIfEncrypted(value: string): string {
	return PAYLOAD_PATTERN.test(value) ? decrypt(value) : value;
}
