import type { Prisma, User } from "../../../prisma/generated/client/client";
import { prisma } from "../../config/prisma";

const planQuotaSelect = { planStatus: true, planExpiresAt: true, freeTransactionCount: true } as const;
export type PlanQuota = Prisma.UserGetPayload<{ select: typeof planQuotaSelect }>;

export const userRepository = {
	findById(id: string): Promise<User | null> {
		return prisma.user.findUnique({ where: { id } });
	},

	findByIdOrThrow(id: string): Promise<User> {
		return prisma.user.findUniqueOrThrow({ where: { id } });
	},

	findByTelegramChatId(chatId: string): Promise<User | null> {
		return prisma.user.findUnique({ where: { telegramChatId: chatId } });
	},

	findPlanQuota(id: string): Promise<PlanQuota> {
		return prisma.user.findUniqueOrThrow({ where: { id }, select: planQuotaSelect });
	},

	async incrementFreeTransactionCount(id: string, by: number): Promise<void> {
		await prisma.user.update({ where: { id }, data: { freeTransactionCount: { increment: by } } });
	},

	update(id: string, data: Prisma.UserUpdateInput): Promise<User> {
		return prisma.user.update({ where: { id }, data });
	},

	async clearAutoGeneratedPassword(id: string): Promise<void> {
		await prisma.user.updateMany({
			where: { id, autoGeneratedPassword: { not: null } },
			data: { autoGeneratedPassword: null },
		});
	},

	async deleteRequestedBefore(cutoff: Date): Promise<number> {
		const result = await prisma.user.deleteMany({ where: { deletionRequestedAt: { lte: cutoff } } });
		return result.count;
	},
};
