import type { User } from "../../../prisma/generated/client/client";
import { decryptIfEncrypted } from "../../lib/encryption";
import { AppError } from "../../lib/errors";
import { hasActivePlan } from "../../lib/plan";
import { userRepository } from "./user.repository";
import type { UpdateProfileInput, UserDTO } from "./user.schema";

export const ACCOUNT_DELETION_GRACE_DAYS = 30;

export class ActivePlanError extends AppError {
	constructor() {
		super(
			"Não é possível excluir a conta enquanto houver um plano ativo. Cancele o plano antes de continuar.",
			409,
		);
	}
}

export function toUserDTO(user: User): UserDTO {
	return {
		id: user.id,
		name: user.name,
		email: user.email,
		emailVerified: user.emailVerified,
		image: user.image,
		twoFactorEnabled: user.twoFactorEnabled,
		planStatus: user.planStatus,
		planExpiresAt: user.planExpiresAt?.toISOString() ?? null,
		freeTransactionCount: user.freeTransactionCount,
		telegramChatId: user.telegramChatId,
		deletionRequestedAt: user.deletionRequestedAt?.toISOString() ?? null,
		autoGeneratedPassword: user.autoGeneratedPassword ? decryptIfEncrypted(user.autoGeneratedPassword) : null,
		createdAt: user.createdAt.toISOString(),
	};
}

export const userService = {
	async getProfile(userId: string): Promise<UserDTO> {
		return toUserDTO(await userRepository.findByIdOrThrow(userId));
	},

	async updateProfile(userId: string, input: UpdateProfileInput): Promise<UserDTO> {
		return toUserDTO(await userRepository.update(userId, input));
	},

	// Free plan: deletion is deferred (soft delete) for ACCOUNT_DELETION_GRACE_DAYS —
	// logging in during that window cancels it (databaseHooks.session.create in
	// lib/auth.ts). The cron route /cron/delete-pending-accounts purges for real.
	async requestDeletion(userId: string): Promise<{ deletionRequestedAt: Date }> {
		const user = await userRepository.findByIdOrThrow(userId);

		if (hasActivePlan(user)) {
			throw new ActivePlanError();
		}

		const deletionRequestedAt = new Date();
		await userRepository.update(userId, { deletionRequestedAt });
		return { deletionRequestedAt };
	},

	purgePendingDeletions(): Promise<number> {
		const cutoff = new Date(Date.now() - ACCOUNT_DELETION_GRACE_DAYS * 24 * 60 * 60 * 1000);
		return userRepository.deleteRequestedBefore(cutoff);
	},
};
