import { z } from "zod";

// `telegramChatId` is deliberately not editable here: linking a chat is only
// possible through an authenticated flow (bot login or the single-use web
// token, see modules/telegram). Letting users type any chat ID let them
// attach someone else's Telegram chat to their account.
export const updateProfileSchema = z.object({
	name: z.string().trim().min(1).max(120).optional(),
	image: z
		.url({ protocol: /^https?$/ })
		.max(2048)
		.optional(),
});

export type UpdateProfileInput = z.infer<typeof updateProfileSchema>;

export type UserDTO = {
	id: string;
	name: string;
	email: string;
	emailVerified: boolean;
	image: string | null;
	twoFactorEnabled: boolean;
	planStatus: string;
	planExpiresAt: string | null;
	freeTransactionCount: number;
	telegramChatId: string | null;
	deletionRequestedAt: string | null;
	autoGeneratedPassword: string | null;
	createdAt: string;
};
