-- AlterTable
ALTER TABLE "user" ADD COLUMN "autoGeneratedPassword" TEXT;

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_two_factor" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "secret" TEXT NOT NULL,
    "backupCodes" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL DEFAULT true,
    "failedVerificationCount" INTEGER NOT NULL DEFAULT 0,
    "lockedUntil" DATETIME,
    CONSTRAINT "two_factor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_two_factor" ("backupCodes", "id", "secret", "userId") SELECT "backupCodes", "id", "secret", "userId" FROM "two_factor";
DROP TABLE "two_factor";
ALTER TABLE "new_two_factor" RENAME TO "two_factor";
CREATE UNIQUE INDEX "two_factor_userId_key" ON "two_factor"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
